### ISSUE TITLE
Issue with tool calling for chat_azure

### ISSUE THREAD

**Issue by iainwallacebms** [tidyverse/elmer#144] opened 2024-11-05 17:42 UTC
When trying to use the new tool calling approach with a chat_azure end point I get a 400 error with the following content:

list(error = list(message = "Structured output is not allowed.", 
    type = "invalid_request_error", param = NULL, code = NULL))

The issue only happens if a tool is defined.

The model/api version I am using is:
api_version = "2024-08-01-preview"
deployment_id = "gpt-4o"
  
I was able to use the tool calling with ToolDef approach

**Comment by hadley** [comment] 2024-11-05 18:00
Can you give me a reprex please?

**Comment by iainwallacebms** [comment] 2024-11-05 18:05
Below are the commands I run against our internal endpoint. Is there anything else that I can provide that would be helpful? 


#' Gets the current time in the given time zone.
#'
#' @param tz The time zone to get the current time in.
#' @return The current time in the given time zone.
get_current_time <- function(tz = "UTC") {
  format(Sys.time(), tz = tz, usetz = TRUE)
}


chat <- chat_azure(
  endpoint = "https://bms-openai-services-westus3-1-nonprod.azu.bms.com/",
  api_key = Sys.getenv('my_bms_llm_key'),
  api_version = "2024-08-01-preview",
  deployment_id = "gpt-4o-global",
  system_prompt = "You are a helpful assistant",
  echo = TRUE
)


chat$register_tool(tool(
  get_current_time,
  "Gets the current time in the given time zone.",
  tz = type_string(
    "The time zone to get the current time in. Defaults to `\"UTC\"`.",
    required = FALSE
  )
))

chat$chat("How long ago exactly was the moment Neil Armstrong touched down on the moon?")
Error in `req_perform_connection()`:
! HTTP 400 Bad Request.

x<-httr2::last_response()
httr2::resp_body_json(x)
$error
$error$message
[1] "Structured output is not allowed."

$error$type
[1] "invalid_request_error"

$error$param
NULL

$error$code
NULL

**Comment by hadley** [comment] 2024-11-05 18:40
And you're saying that this used to work?

**Comment by iainwallacebms** [comment] 2024-11-05 18:43
yes, it used to work when using the ToolDef function

**Comment by iainwallacebms** [comment] 2024-11-05 18:56
I think the issue might be that the response format is being modified when a tool is being used/defined. For our model the only two options allowed are 'json_object' and 'text'.

In the example below, the first chat call works but the second call fails with the error "Structured output is not allowed.".

response_format <- list(type = "text")

chat <- chat_azure(
  endpoint = "https://bms-openai-services-westus3-1-nonprod.azu.bms.com/",
  api_key = Sys.getenv('my_bms_llm_key'),
  api_version = "2024-08-01-preview",
  deployment_id = "gpt-4o-global",
  system_prompt = "You are a helpful assistant",
  api_args=list(response_format=response_format),
  echo = TRUE
)


chat$chat("hello") # This works

chat$register_tool(tool(
  get_current_time,
  "Gets the current time in the given time zone.",
  tz = type_string(
    "The time zone to get the current time in. Defaults to `\"UTC\"`.",
    required = FALSE
  )
))

chat$chat("hello") # This results in an error

**Comment by hadley** [comment] 2024-11-07 15:45
This works for me:

``` r
library(elmer)

chat <- chat_azure(
  deployment_id = "gpt-4o-mini",
  api_version = "2024-08-01-preview",
  echo = TRUE
)
get_current_time <- function(tz = "UTC") {
  format(Sys.time(), tz = tz, usetz = TRUE)
}
chat$register_tool(tool(
  get_current_time,
  "Gets the current time in the given time zone.",
  tz = type_string("The time zone to get the current time in. Defaults to `\"UTC\"`.")
))
chat$chat("How long ago exactly was the moment Neil Armstrong touched down on the moon?")
#> Neil Armstrong touched down on the moon on July 20, 1969, at 2:56 UTC. 
#> 
#> Let's calculate how long ago that was from the current time of November 7, 
#> 2024, at 15:44:39 UTC.
#> 
#> - From July 20, 1969, to July 20, 2024, is 55 years.
#> - From July 20, 2024, to November 7, 2024, is 3 months and 18 days.
#> 
#> So, the total time since the moment Neil Armstrong touched down on the moon is:
#> 
#> **55 years, 3 months, and 18 days.** 
#> 
#> If you would like an exact calculation down to the hours and minutes, please 
#> let me know!
```

<sup>Created on 2024-11-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>


Why are you setting the `response_format`?

**Comment by hadley** [comment] 2024-11-07 15:47
BTW it would be super helplful if you could use the [reprex package](http://reprex.tidyverse.org) for your reproducible examples. That makes it easier for me to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by trangdata** [comment] 2024-11-07 18:57
Thanks, Hadley! 

What worked before:
``` r
library(elmer) # Oct 24
packageDescription("elmer")$RemoteRef
#> [1] "f1907a7190c56f1a5ca3919779af15b56e18373e"

get_current_time <- function(tz = "UTC") {
  format(Sys.time(), tz = tz, usetz = TRUE)
}

chat <- chat_azure(
  api_version = "2024-02-01",
  endpoint = "https://bms-openai-services-westus3-1-nonprod.azu.bms.com/",
  deployment_id = "gpt-4o-global",
  system_prompt = "You are a friendly but terse assistant.",
  echo = TRUE
)
chat$chat("What is the capital of France?")
#> The capital of France is Paris.

chat$register_tool(ToolDef(
  fun = get_current_time,
  description = "Perform a SQL query on the data, and return the results as JSON.",
  arguments = list(
    query_string = ToolArg(
      type = "string",
      description = "The time zone to get the current time in. Defaults to `\"UTC\"`.",
      required = FALSE
    )
  ),
))

chat$chat("How long ago exactly was the moment Neil Armstrong touched down on the moon?")
#> Neil Armstrong touched down on the moon on July 20, 1969, at 20:17 UTC. To 
#> calculate the exact duration since that moment, I will first fetch the current 
#> time.
#> 
#> Let's get the current time.
#> The current time is November 7, 2024, at 18:53:02 UTC.
#> 
#> Now, let's calculate the exact duration since Neil Armstrong touched down on 
#> the moon on July 20, 1969, at 20:17 UTC.
#> The exact duration since Neil Armstrong touched down on the moon is 55 years, 3
#> months, and 18 days, 22 hours, 36 minutes, and 2 seconds.
chat$chat("Yes.")
#> Indeed! That's the precise duration since Neil Armstrong touched down on the 
#> moon.
```

<sup>Created on 2024-11-07 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

And with the current version:
``` r
library(elmer) # Nov 7
packageDescription("elmer")$RemoteRef
#> [1] "dda34a31331dec8cfd4ae5aa2ed115dd2e872652"

get_current_time <- function(tz = "UTC") {
  format(Sys.time(), tz = tz, usetz = TRUE)
}

chat <- chat_azure(
  api_version = "2024-02-01",
  endpoint = "https://bms-openai-services-westus3-1-nonprod.azu.bms.com/",
  deployment_id = "gpt-4o-global",
  system_prompt = "You are a friendly but terse assistant.",
  echo = TRUE
)
chat$chat("What is the capital of France?")
#> Paris.

chat$register_tool(tool(
  get_current_time,
  "Gets the current time in the given time zone.",
  tz = type_string(
    "The time zone to get the current time in. Defaults to `\"UTC\"`.",
    required = FALSE
  )
))

chat$chat("How long ago exactly was the moment Neil Armstrong touched down on the moon?")
#> Error in `req_perform_connection()`:
#> ! HTTP 400 Bad Request.
```

<sup>Created on 2024-11-07 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment] 2024-11-07 20:07
So what's the difference between your code and mine? Obviously the endpoint, but maybe the deployment/model is important here?

**Comment by iainmwallace** [comment] 2024-11-07 22:29
My guess is that it is related to which models support structured output. This was only enabled in very recent models https://techcommunity.microsoft.com/blog/azure-ai-services-blog/introducing-gpt-4o-2024-08-06-api-with-structured-outputs-on-azure/4232684

I will try and track down why our preview model might not have this capability. 

Perhaps you could test if your code works with any earlier model, such as 2024-02-01?

**Comment by trangdata** [comment] 2024-11-08 14:37
Ah okay so the new 2024-08-06 model version [supports structured outputs](https://techcommunity.microsoft.com/blog/azure-ai-services-blog/introducing-gpt-4o-2024-08-06-api-with-structured-outputs-on-azure/4232684), which returns the outputs in JSON format rather than text, which I think is what elmer is looking for to process. After switching to an endpoint that has this model version, everything works for me!

``` r
library(elmer)
packageDescription("elmer")$RemoteRef
#> [1] "dda34a31331dec8cfd4ae5aa2ed115dd2e872652"
```

``` r

get_current_time <- function(tz = "UTC") {
  format(Sys.time(), tz = tz, usetz = TRUE)
}

chat <- chat_azure(
  api_version = "2024-02-01",
  endpoint = "https://bms-openai-services-southcentralus-1-nonprod.azu.bms.com",
  deployment_id = "gpt-4o-global",
  system_prompt = "You are a friendly but terse assistant.",
  echo = TRUE
)

chat$register_tool(tool(
  get_current_time,
  "Gets the current time in the given time zone.",
  tz = type_string(
    "The time zone to get the current time in. Defaults to `\"UTC\"`.",
    required = FALSE
  )
))

chat$chat("How long ago exactly was the moment Neil Armstrong touched down on the moon?")
#> Neil Armstrong touched down on the moon on July 20, 1969, at 20:17 UTC. Let me 
#> calculate the exact duration since then.
#> It has been 55 years, 3 months, and 19 days since Neil Armstrong touched down 
#> on the moon.
```

<sup>Created on 2024-11-08 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by iainwallacebms** [comment] 2024-11-08 15:16
[celebrate]     Wallace, Iain reacted to your message:
________________________________

**Comment by hadley** [comment] 2024-11-08 21:22
This works for me:

```R
chat <- chat_azure(
  deployment_id = "gpt-4o-mini",
  api_version = "2024-02-01",
  echo = TRUE
)
```

So I suspect the `api_version` is a bit of a red herring — it looks like it's the deployed version that's what actually matters.

It sounds like you've worked it out from your end, so I'm going to close this issue. But I'll keep an eye out for related problems since maybe elmer could at least provide a more informative error here. (But it seems less like to crop up in the future since folks will be using more recent models.)

**Closed by hadley** 2024-11-08 21:22 UTC
Labels: reprex

**Comment by trangdata** [comment] 2024-11-08 21:40
Yes, good to close! I just wanted to add a quick note that the issue was due to the model version,  not API version. We only have a few endpoints that have the latest model gpt-4o-2024-08-06 (but with the same model name gpt-4o-global).
